name: Run all tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install z80asm
      run: sudo apt-get install -y z80asm

    - name: Re-assemble original binary
      run: make all

    - name: 'Upload build artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
            out.bin
            out.lst
